version: '3'
services:
  talker:
    build: ./
    volumes:
      - ./images:/images
      - ./wavs:/wavs
      - ./movies:/movies
    working_dir: /app/SadTalker
    command: uvicorn voicevox-sadtalker:app --reload  --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
    networks:
      - chat-network
    deploy:
      resources:
          reservations:
              devices:
                  - capabilities: [gpu]
    environment: 
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=all
  
  voice-engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - 50021:50021
    networks:
      - chat-network

networks:
  chat-network: